"""chats tabel alter

Revision ID: 193dbd8ff520
Revises: 520badf6e89f
Create Date: 2026-06-10 16:12:53.065913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193dbd8ff520'
down_revision: Union[str, Sequence[str], None] = '520badf6e89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_last_message_at'), 'chats', ['last_message_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_last_message_at'), table_name='chats')
    # ### end Alembic commands ###
