"""chats tabel alter

Revision ID: 520badf6e89f
Revises: eab231f90872
Create Date: 2026-06-10 16:07:59.549915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520badf6e89f'
down_revision: Union[str, Sequence[str], None] = 'eab231f90872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message_id', sa.UUID(), nullable=True))
    op.add_column('chats', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'chats', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'last_message_at')
    op.drop_column('chats', 'last_message_id')
    # ### end Alembic commands ###
