"""chat model alter

Revision ID: 67a3ba3fabf7
Revises: a95c1d8110cb
Create Date: 2026-06-20 13:29:42.270581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a3ba3fabf7'
down_revision: Union[str, Sequence[str], None] = 'a95c1d8110cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_message_id', sa.UUID(), nullable=True))
    op.add_column('chats', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chats_last_message_at'), 'chats', ['last_message_at'], unique=False)
    op.create_foreign_key(None, 'chats', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_last_message_at'), table_name='chats')
    op.drop_column('chats', 'last_message_at')
    op.drop_column('chats', 'last_message_id')
    # ### end Alembic commands ###
