"""last_delevered_message add in chat_paricipants table

Revision ID: 88ac3b81312b
Revises: b17f59dfb321
Create Date: 2026-06-13 11:28:09.631021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ac3b81312b'
down_revision: Union[str, Sequence[str], None] = 'b17f59dfb321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('last_delivered_message_id', sa.UUID(), nullable=True))
    op.add_column('chat_participants', sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chat_participants_last_delivered_message_id'), 'chat_participants', ['last_delivered_message_id'], unique=False)
    op.create_foreign_key(None, 'chat_participants', 'messages', ['last_delivered_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.drop_index(op.f('ix_chat_participants_last_delivered_message_id'), table_name='chat_participants')
    op.drop_column('chat_participants', 'last_delivered_at')
    op.drop_column('chat_participants', 'last_delivered_message_id')
    # ### end Alembic commands ###
