"""user profile table alter

Revision ID: c65e60f43833
Revises: 88ac3b81312b
Create Date: 2026-06-19 11:04:03.145215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65e60f43833'
down_revision: Union[str, Sequence[str], None] = '88ac3b81312b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_email', 'user_profiles', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_email', 'user_profiles', type_='unique')
    # ### end Alembic commands ###
