"""chats tabel alter

Revision ID: cabacbc99714
Revises: 193dbd8ff520
Create Date: 2026-06-10 16:19:23.766361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabacbc99714'
down_revision: Union[str, Sequence[str], None] = '193dbd8ff520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('chats', sa.Column('image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'image')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
